version: '2.2'
services:
  es01:
    build: .
    container_name: es01
    environment:
    - node.name=es01
    - cluster.initial_master_nodes=es01
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

#  python:
#    build: python/
#    depends_on:
#      - es01
#    networks:
#      - esnet
#    container_name: python_script

volumes:
  esdata1:
    driver: local

networks:
  esnet:
